### ISSUE TITLE
Need more info about pins

### ISSUE THREAD

**Issue by idsidorov** [FoodNicheGIT/FoodNicheRest#12]
We need to get  two more  fields in this request - FoodNicheRest/businesses
1) Restaurant type (vegetarian, stake house, sea food)
2) Number of reviews

**Comment by aaborschenko** [comment]
@adubrov @atmman @niyioyelade 
started

**Comment by aaborschenko** [comment]
PR #14 
1) use **businessType.name** property
2) added **raves** property

See example JSON below
`{
    "businessid": 1,
    "businessType": {
      "businesstypeid": 0,
      "name": "Fast casual restaurant"
    },
    "name": "Zorend",
    "zipCode": "95969",
    "website": "www.tastyfood.com",
    "description": "xvcxcvb",
    "lat": 39.7213638,
    "lon": -121.6511258,
    "likes": 0,
    "raves": 0
  }`

Pushed to QA and PROD

Please verify. 
Thanx!

**Comment by atmman** [comment]
@aaborschenko 

Issue is fixed.
Thank you.
