### ISSUE TITLE
Need image for coupons

### ISSUE THREAD

**Issue by atmman** [FoodNicheGIT/FoodNicheRest#15]
@aaborschenko 
We need have **couponPictureURL** field for coupon.

Thank you.

**Comment by aaborschenko** [comment]
@atmman I guess we also need API endpoint to upload pictures for coupons?

**Comment by atmman** [comment]
@aaborschenko yes.

**Comment by aaborschenko** [comment]
starting today

**Comment by aaborschenko** [comment]
@idsidorov @niyioyelade @atmman 
I need to figure it out how Coupons should be managed.
Do they belong to some business?

We upload any picture under specific User permissions. So I need to check if target Coupon is somehow related to that User. Then Coupon can reference uploaded picture.

Asked Bola for clarification in Skype chat.

If anyone has info please let me know.
Thanx!

**Comment by aaborschenko** [comment]
Clarified with Bola in skype chat:

> [8:04:29 PM | Edited 8:04:38 PM] Alexey Borschenko: How coupons should be managed?
Do they belong to some business... ?
[8:58:18 PM] Bola O: Yes, coupons are provided by businesses
[8:58:45 PM] Alexey Borschenko: Makese sense now
[8:59:08 PM] Alexey Borschenko: I will update db to reference coupons by business
[8:59:27 PM] Bola O: Thanks
[8:59:32 PM] Alexey Borschenko: And will update coupon management api accordingly
[8:59:47 PM] Alexey Borschenko: Thanx for fast response ;)

**Comment by aaborschenko** [comment]
* add reference in Coupon to Business
* add security checks if Coupon belongs to User's Business
* update Coupon management services accordingly

**Comment by niyioyelade** [comment]
Bola is the authority on how coupons work but I know businesses are the. One who issue coupons

**Comment by aaborschenko** [comment]
@niyioyelade 
Yes. Saw this already. No need to add double reference here. Refactoring coupons management now.

**Comment by aaborschenko** [comment]
PR #18 
Merged to master,
Pushed to QA and PROD.

Refactored Coupons management
New API endpoints: http://api-qa.foodniche.me/swagger/#!/apicoupons

Also includes changes in Upload Image responses for Profile and Coupon as described in Issue #17 

@atmman 
Please verify.
Thanx!

**Comment by aaborschenko** [comment]
@atmman @idsidorov 
any updates?

**Comment by atmman** [comment]
@aaborschenko 
It looks good.

Thank you.
