### ISSUE TITLE
Profile picture endpoit

### ISSUE THREAD

**Issue by atmman** [FoodNicheGIT/FoodNicheRest#17]
@aaborschenko 
We need to get data in response. Data example below
 {
  "fileId": 163,
  "serverFileName": "1455301288393-03e909bd-75ae-4c1b-ac6d-0f4d69a11c99-BudRpdgvTDA.jpg",
  "fileName": "BudRpdgvTDA.jpg",
  "contentType": "image/jpeg",
  "fileSize": 226383,
  "fileType": "IMAGE",
  "url": ""
}

We receive such data in image upload request. 

Thank you

**Comment by aaborschenko** [comment]
@niyioyelade @idsidorov @atmman 
Pushed to QA and PROD as part of Issue #15 

Please verify.
Thanx!

**Comment by aaborschenko** [comment]
@atmman @idsidorov 
any updates?

**Comment by atmman** [comment]
@aaborschenko 
I have checked it. It works excellent.
Thank you.
