### ISSUE TITLE
Login endpoint for business must return business + user info

### ISSUE THREAD

**Issue by aaborschenko** [FoodNicheGIT/FoodNicheRest#7]
Now login returns or Business or User
We need to get User and if it is a business account then include Business entity

**Comment by aaborschenko** [comment]
@idsidorov @atmman 
started

**Comment by aaborschenko** [comment]
Endpoint to be fixed is */api/user/profile*

**Comment by aaborschenko** [comment]
#8 PR here

**Comment by aaborschenko** [comment]
PR merged

**Comment by aaborschenko** [comment]
Pushed to QA

**Comment by aaborschenko** [comment]
@atmman please verify and confirm

Now it will always return Users entity. 
If it is business account then it will contain Businesses entity under **business** property

**Comment by atmman** [comment]
@aaborschenko it is ok. 

Thank you.

**Comment by aaborschenko** [comment]
Closing
