### ISSUE TITLE
Add API endpoint for uploading user profile picture

### ISSUE THREAD

**Issue by aaborschenko** [FoodNicheGIT/FoodNicheRest#9]
We need single API method for uploading user profile pic.
It must store **com.foodniche.db.entities.UploadedFiles** entity, then link it to corresponding **Users** entity.
In response it will return image URL.

**Comment by aaborschenko** [comment]
@idsidorov @niyioyelade @atmman 
work started

**Comment by aaborschenko** [comment]
Pull Request: #10

**Comment by aaborschenko** [comment]
Added API endoint.

**http://api-qa.foodniche.me/swagger/#!/files/uploadProfilePicture**
This uploads image and assigns it as profile picture to current user profile

Pushed to QA and PROD

**Comment by aaborschenko** [comment]
Refactored files API
Added new property to **Users** entity **profilePictureURL**
In response of reading user profile it will contain URL to profile pic if it is uploaded.

Created additional PR: #11.
Merged.

Pushed to QA and PROD

@atmman please verify and confirm
Thanx!

**Comment by aaborschenko** [comment]
@atmman any updates here?

**Comment by atmman** [comment]
@aaborschenko 
Something is wrong.
I see an error when I try to upload picture. I have tried to make request via Swagger UI.

You can see it here:
http://pastebin.com/YcjZYzz2

**Comment by aaborschenko** [comment]
@atmman 
please try setting 
**--header "Content-Type: image/jpeg"**

**Comment by atmman** [comment]
@aaborschenko 

I have tried it. I see another error.

pastebin:
http://pastebin.com/22xPWMxk

**Comment by atmman** [comment]
Also I see similar error when I try to make POST request in /api/files/image.

**Comment by aaborschenko** [comment]
@atmman 
Fixed.
Added maximum file size checks.
Image: 10000000 bytes
Video: 20000000 bytes

PR #13 

Pushed to QA and PROD

Please verify

**Comment by atmman** [comment]
@aaborschenko 
It is okay. Issue is fixed.

Thank you.
